displayName: web api secrets test
testPlan: url-test.json
description: Tests a web API using secrets from AKV
engineInstances: 2
testId: 1e6fabaa-23d0-4042-aa42-9080189c51b0
testType: URL
subnetId: /subscriptions/24ef1668-95f3-4c77-adf2-2d023271a3e1/resourceGroups/rg-load-test/providers/Microsoft.Network/virtualNetworks/rg-load-test-vnet/subnets/alt
publicIPDisabled: false
splitAllCSVs: False
failureCriteria: []
secrets:
- name: apikey
  value: https://azureloadtestvault.vault.azure.net/secrets/apikey
autoStop:
  errorPercentage: 90
  timeWindow: 60
