name: Load Testing Demo
run-name: Making a sample pipeline
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDS }}
      - name: Azure Load Testing
        uses: Azure/load-testing@v1.1.21
        with:
          # Path of the YAML file. Should be fully qualified path or relative to the default working directory
          loadtestConfigFile: "demoapp.yml"
          # Enter or Select the name of an existing Azure Load Testing resource
          loadtestResource: "binarydad"
          # Custom name for the load test run
          loadtestRunName: "CICD test run" # optional
          # Custom description for the load test run
          #loadtestRunDescription: # optional
          # Enter or Select the Azure Resource Group that contains the Load test resource specified above
          resourceGroup: "rg-load-test"
          # Enter secrets in JSON
          #secrets: # optional
          # Enter env in JSON
          #env: # optional
